PSC06/Controllers/CerrarSessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PSC06.Controllers
{
    public class CerrarSessionController : Controller
    {
        // GET: CerrarSession
        public ActionResult Logoff()
        {
            Session["Usuario"] = null;
            return RedirectToAction("Login", "Acceder");
        }
    }
}

PSC06/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PSC06.Models;
using PSC06.Models.TableViewModel;
using PSC06.Models.ViewModel;

namespace PSC06.Controllers
{
    public class UserController : Controller
    {
        // GET: Query
        public ActionResult Query()
        {
            List<UserTableViewModel> lst = null;

            using (DBAutosEntities db =  new DBAutosEntities())
            {
                // SELECT * FROM USER WHERE IDESTATUS = 1
                lst = (from d in db.USERs
                       where d.idEstatus == 1
                       orderby d.Email

                       select new UserTableViewModel
                       {
                           _Email = d.Email,
                           _Id = d.ID,
                           _Edad = d.Edad
                       }).ToList();
            }

            return View(lst);
        }


        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(AddUserViewModels model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new DBAutosEntities())
            {
                USER oUser = new USER();
                oUser.idEstatus = 1;
                oUser.Email = model.Email;
                oUser.Nombre = model.Nombre;
                //oUser.Edad = model.Edad;
                oUser.PassWord = model.Password;

                db.USERs.Add(oUser);
                db.SaveChanges();
            }

            return Redirect(Url.Content("~/User/Query"));
        }
    }
}

PSC06/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Seccion 06</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Consulta Usuario", "Query", "User")</li>

                    <li>@Html.ActionLink("Cerrar Session", "Logoff", "CerrarSession")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Seccion 06</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PSC06/Views/Shared/_LayoutAcceder.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Seccion 06</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .loginform_main {
            width: 80vw;
            height: 25vw;
            max-width: 600px;
            margin: 0 auto;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            background-color: rgb(255, 255, 255);
            padding: 4vh 4vw; /* 4% del alto y ancho de la ventana gráfica */
            box-shadow: 0px 0px 40px rgba(0, 0, 0, 0.062);
            position: relative;
            overflow: hidden;
            border-radius: 10px;
            transition: border-radius 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275);
            box-shadow: inset 0 -3em 3em rgba(0,0,0,0.1), 0 0 0 2px rgb(190, 190, 190), 0.3em 0.3em 1em rgba(0,0,0,0.3);
        }

            .loginform_main::before {
                position: absolute;
                content: "";
                width: 400px;
                height: 300px;
                background-color: rgb(209, 193, 255);
                transform: rotate(45deg);
                left: -180px;
                bottom: 30px;
                z-index: 1;
                border-radius: 30px;
                box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.082);
            }

        .loginheading {
            font-size: 2em;
            color: #2e2e2e;
            font-weight: 700;
            margin: 5px 0 10px 0;
            z-index: 2;
        }

        .loginrow {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh; /* Altura del 100% de la ventana */
        }

        .logininputContainer {
            width: 100%;
            position: relative;
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 2;
        }

        .logininputIcon {
            position: absolute;
            left: 3px;
        }

        .logininputField {
            width: 100%;
            height: 30px;
            background-color: transparent;
            border: none;
            border-bottom: 2px solid rgb(173, 173, 173);
            margin: 10px 0;
            color: black;
            font-size: .8em;
            font-weight: 500;
            box-sizing: border-box;
            padding-left: 30px;
        }

            .logininputField:focus {
                outline: none;
                border-bottom: 2px solid rgb(199, 114, 255);
            }

            .logininputField::placeholder {
                color: rgb(80, 80, 80);
                font-size: 1em;
                font-weight: 500;
            }

        .loginbtn {
            z-index: 2;
            position: relative;
            width: 100%;
            border: none;
            background-color: rgb(162, 104, 255);
            height: 30px;
            color: white;
            font-size: .8em;
            font-weight: 500;
            letter-spacing: 1px;
            margin: 10px;
            cursor: pointer;
        }

        #loginbutton:hover {
            background-color: rgb(126, 84, 255);
        }

        .loginforgotLink {
            z-index: 2;
            font-size: .7em;
            font-weight: 500;
            color: rgb(44, 24, 128);
            text-decoration: none;
            padding: 8px 15px;
            border-radius: 20px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Seccion 06</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>